
package com.sliit.oop_serverapp.entity;

import jakarta.persistence.*; // JPA annotations for database mapping
import jakarta.validation.constraints.Size; // Validation for string length
import lombok.Getter;
import lombok.Setter;

/**
 * Category Entity Class
 * ---------------------
 * This class represents the "category" table in the database.
 * It is used to store category details such as category ID and name.
 *
 * OOP Concepts Used:
 * 1. Encapsulation
 *    - Data members are kept private.
 *    - Access is provided through getters and setters.
 *
 * 2. Data Modeling
 *    - This entity models a real-world category object.
 *
 * Technologies Used:
 * - JPA/Hibernate for ORM mapping
 * - Lombok for automatic getter/setter generation
 * - Jakarta Validation for input validation
 */

@Getter // Lombok automatically generates getter methods
@Setter // Lombok automatically generates setter methods
@Entity // Marks this class as a JPA entity
@Table(name = "category") // Maps this entity to the "category" table

public class Category {

    /**
     * Primary Key of the category table
     * AUTO_INCREMENT value generated by the database
     */
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates ID values
    @Column(name = "id", nullable = false) // Maps field to "id" column
    private Integer id;

    /**
     * Name of the category
     * Maximum length allowed is 45 characters
     */
    @Size(max = 45) // Validation: name cannot exceed 45 characters
    @Column(name = "name", length = 45) // Maps field to "name" column
    private String name;

}

